name: Linux

on:
   push:
      branches: [ master ]
   pull_request:

jobs:

   build:
      name: build
      runs-on: ubuntu-20.04

      steps:
      - name: checkout
        uses: actions/checkout@v2.3.3
        with:
           submodules: recursive
      - name: update package lists
        continue-on-error: true
        run: sudo apt update
      - name: install boost
        run: sudo apt install libboost-tools-dev libboost-dev libboost-system-dev
      - name: build tools
        run: b2 link=static stage
      - name: test
        run: python3 test/test.py
