name: Tests

on:
   push:
      branches: [ master ]
   pull_request:

jobs:

   build:
      name: build
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest ]

      steps:
      - name: checkout
        uses: actions/checkout@v2.3.3
        with:
           submodules: recursive
      - name: update package lists (Linux)
        continue-on-error: true
        if: runner.os == 'Linux'
        run: sudo apt update
      - name: dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install libboost-tools-dev libboost-dev libboost-system-dev
      - name: dependencies (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew install boost-build boost
          echo "using darwin ;" >> ~/user-config.jam
      - name: build tools
        run: b2 link=static stage
      - name: test
        run: python3 test/test.py
